[package]
name = "SolinBlog"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
getrandom = "0.2"
axum = "0.7"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
percent-encoding = "2"
